package com.example.slider_fragments

import android.os.Bundle
import com.google.android.material.floatingactionbutton.FloatingActionButton
import com.google.android.material.snackbar.Snackbar
import com.google.android.material.tabs.TabLayout
import androidx.viewpager.widget.ViewPager
import androidx.appcompat.app.AppCompatActivity
import android.view.Menu
import android.view.MenuItem
import com.example.slider_fragments.ui.main.SectionsPagerAdapter
// here we have added some codes in placeholder.kt file in java folder check it
// remove fab code in folders
// we have selected Tabbed Activity and all code is autogenerated in our files
// main pages changes in our fragment_main.xml file
// we just add widgets not include title and src of compat
// all images and titles are set in placeholder.kt check it
// if you want to use 10 fragments pages then go to SectionsPagerAdapter.kt
// and in getCount():Int return 10 it will load 10 pages
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        val  sectionsPagerAdapter = SectionsPagerAdapter(this, supportFragmentManager)
        val viewPager: ViewPager = findViewById(R.id.view_pager)
        viewPager.adapter = sectionsPagerAdapter



    }
}